# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

include ../Makefile.opts

APP_NAME := tiny-string-tests
ARDUINO_LIBS := AUnit AceCommon AceTime TinyConsole
ARDUINO_LIB_DIRS := ../../../EspMock/libraries
EPOXY_CORE := EPOXY_CORE_ESP8266
include ../EpoxyDuino.mk
